start_point = 0xF4000
global_emotes = true
channels = ["togglebit", "modprog"]
custom_emotes = "./custom"
output_font = "./twitchmotes.ttf"
output_map = "./map.csv"
emote_scale = 3
parallel_downloads = 32
